---
bases:
  - ../../base

namespace: dev
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
    path: replicas.yaml

configMapGenerator:
  - name: mykustom-map
    env: config.properties
